/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#874f4f',
        'on-primary': '#ffffff',
        'primary-container': '#e8a2a2',
        'on-primary-container': '#6a3738',
        'inverse-primary': '#fcb4b4',
        'primary-fixed': '#ffdad9',
        'primary-fixed-dim': '#fcb4b4',
        secondary: '#615e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e8e1dd',
        'on-secondary-container': '#686461',
        tertiary: '#575f6a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#adb5c1',
        'on-tertiary-container': '#3f4751',
        surface: '#fbf9f8',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#524343',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        outline: '#847373',
        'outline-variant': '#d6c2c1',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0px 4px 20px rgba(232, 162, 162, 0.12)',
        modal: '0px 12px 40px rgba(0, 0, 0, 0.05)',
        card: '0px 2px 12px rgba(135, 79, 79, 0.08)',
      },
    },
  },
  plugins: [],
}

